version: '3'
services:
    apache:
        build: apache
        container_name: ${PROJECT_NAME}-apache
        ports:
          - '80:80'
        volumes:
          - ./config/vhosts:/etc/apache2/sites-enabled
          - ..:/app
        depends_on:
          - php

    # mysql:
    #     image: mysql:8
    #     container_name: sf4_mysql
    #     volumes:
    #         - .docker/data/db:/var/lib/mysql
    #     command:
    #         - "--default-authentication-plugin=mysql_native_password"
    #         - "--lower_case_table_names=1"
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: sf4
    #         MYSQL_USER: sf4
    #         MYSQL_PASSWORD: sf4

    php:
        build: ./php
        container_name: ${PROJECT_NAME}-php
        volumes:
          - ..:/app
          - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        # depends_on:
        #   - mysql

    redis:
        build: ./redis
        container_name: ${PROJECT_NAME}-redis
        image: 'redis:6.0.5'
        ports:
          - '6379:6379'